service zookeeper-server start
service sqoop-metastore start
service sqoop2-server start
service spark-history-server start
service solr-server start
service oozie start
service impala-state-store start
service impala-server start
service impala-catalog start
service hive-server2 start
service hive-metastore start
service hbase-thrift start
service hbase-solr-indexer start
service hbase-rest start
service hbase-regionserver start
service hbase-master start
service hadoop-yarn-resourcemanager start
service hadoop-yarn-proxyserver start
service hadoop-yarn-nodemanager start
service hadoop-mapreduce-historyserver start
service hadoop-httpfs start
service hadoop-hdfs-secondarynamenode start
service hadoop-hdfs-namenode start
service hadoop-hdfs-journalnode start
service hadoop-hdfs-datanode start
